### ISSUE TITLE
Laggy music

### ISSUE THREAD

**Issue by ImAleeexx** [Snowflake107/discord-ytdl-core#19] opened 2021-02-09 00:40 UTC
Im having a issue with a bot, the music is speeding up or lagging
Has anyone had any type of issue like this?

**Comment by twlite** [comment] 2021-02-09 05:35
might be an issue with your internet

**Comment by ImAleeexx** [comment] 2021-02-10 08:02
Mmmh, That seems little bit strange as im using an OVH dedicated server and it is practically empty. Any other idea?

**Comment by twlite** [comment] 2021-02-10 08:07
it also depends upon your rtc latency (Discord voice latency)

**Comment by ImAleeexx** [comment] 2021-02-10 08:49
100-110ms, is that too much?

**Comment by twlite** [comment] 2021-02-22 14:13
voice latency is different from regular ws latency, might be server region or something like that. This problem is not caused by this library. And I'm closing this issue now. If you have any issue(s) related to this library, feel free to open a new one 👍

**Closed as completed by twlite** 2021-02-22 14:13 UTC
Labels: help wanted
